// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Detail: typeof import('./src/components/Detail.vue')['default']
    Div: typeof import('vue-termui')['TuiBox']
    Header: typeof import('./src/components/Header.vue')['default']
    Link: typeof import('vue-termui')['TuiLink']
    Nodes: typeof import('./src/components/Nodes.vue')['default']
    Span: typeof import('vue-termui')['TuiText']
    Topics: typeof import('./src/components/Topics.vue')['default']
  }
}
